name: Frontend Deploy

on:
  push:
    branches: ["main"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            set -e

            cd /home/pmdweb/psc/frontend
            git pull origin main

            # Build
            npm install
            npm run build

            # Clean target safely
            echo "${{ secrets.SERVER_PASS }}" | sudo -S mkdir -p /var/www/psc/frontend
            echo "${{ secrets.SERVER_PASS }}" | sudo -S rm -rf /var/www/psc/frontend/*

            # Copy build
            echo "${{ secrets.SERVER_PASS }}" | sudo -S cp -r dist/* /var/www/psc/frontend/

            # Reload nginx
            echo "${{ secrets.SERVER_PASS }}" | sudo -S systemctl reload nginx